# Chapter 3: Introduction to NumPy



In [1]:
import numpy as np
np.__version__

'1.9.2'

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set() # for plot styling

## Understanding Data Types in Python

Users of Python are often drawn-in by its ease of use, one piece of which is dynamic
typing. While a statically-typed language like C or Java requires each variable to be
explicitly declared, a dynamically-typed language like Python skips this specification.

For example, in C you might specify a particular operation as follows:

``` c
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

While in Python the equivalent operation could be written this way:

``` python
# Python code
result = 0
for i in range(100):
    result += i
```

Notice the main difference: in C, the data types of each variable are explicitly
declared, while in Python the types are dynamically inferred. This difference certainly
contributes to the ease Python provides for translating algorithms to code, but to
really understand data in Python we must first understand what is happening under
the hood.

As we have mentioned several times, Python variables are dynamically typed. This
means, for example, that we can assign any kind of data to any variable:

``` python
# Python code
x = 4
x = "four"
```

Here we’ve switched the contents of x from an integer to a string.
The same thing in C would lead (depending on compiler settings) to a compilation
error or other unintented consequences:

``` c
/* C code */
int x = 4;
x = "four"; // FAILS
```

This sort of flexibility is one piece that makes Python and other dynamically-typed
languages convenient and easy to use. Understanding how this works is an important
piece of learning to analyze data efficiently and effectively with Python. But what this
type-flexibility also points to is the fact that Python variables are more than just their
value; they also contain extra information about the type of the value.

### A Python Integer is More than just an Integer

The standard Python implementation is written in C. This means that every Python
object is simply a cleverly-disguised C structure, which contains not only its value,
but other information as well.

For example, when we define an integer in Python,

``` python
x = 10000
```

x is not just a “raw” integer. It’s actually a pointer to a compound C structure, which
contains several values Looking through the Python 3.4 source code, we find that the
long integer type definition effectively looks like this (once the C macros are expanded):

``` c
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

A single integer in Python 3.4 actually contains four pieces:

- ob_refcnt, a reference count which helps Python silently handle memory allocation and deallocation
- ob_type, which encodes the type of the variable
- ob_size, which specifies the size of the following data members
- ob_digit, which contains the actual integer value that we expect the Python variable to represent.

This means that there is some overhead in storing an integer in Python as compared
to an integer in a compiled language like C.

A C integer is essentially a label for a position in memory
whose bytes encode an integer value. A Python integer is a pointer to a position in
memory containing all the Python object information, including the bytes which
contain the integer value. This extra information in the Python integer structure is
what allows Python to be coded so freely and dynamically. All this additional information in Python types comes at a cost, however, which becomes especially apparent
in structures which combine many of these objects.

### A Python List is More than just a List

In [3]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

This flexibility comes at a cost: to allow these flexible types, each item in the list
must contain its own type info, reference count, and other information; that is, each
item is a complete Python object. In the special case that all variables are of the same
type, much of this information is redundant: it can be much more efficient to store
data in a fixed-type array.

At the implementation level, the array essentially contains a single pointer to one contiguous
block of data. The Python list, on the other hand, contains a pointer to a
block of pointers, each of which in turn points to a full Python object like the Python
integer we saw above. Again, the advantage of the list is flexibility: because each list
element is a full structure containing both data and type information, the list can be
filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility,
but are much more efficient for storing and manipulating data.

### Fixed-type arrays in Python

Python offers several different options for storing data in efficient, fixed-type data
buffers. Built-in since Python 3.3 is the array module, which can be used to create
dense arrays of a uniform type:

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here "i" is a type code indicating the contents are integers. Much more useful, however,
is the ndarray object of the NumPy package. While Python’s array obnject provides
efficient storage of array-based data, NumPy adds to this efficient operations on
that data. We will explore these operations in later sections; here we’ll demonstrate
several ways of creating a numpy array.

## Creating Arrays from Python Lists

In [5]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14, 2, 2, 3])

array([ 3.14,  2.  ,  2.  ,  3.  ])

In [7]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [8]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays from scratch

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a (3 x 5) floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
# Crate a (3 x 5) array filled with 3.14
np.full((3, 5), 3.14)

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

In [ ]:
# Create an array of 5 values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

In [ ]:
# Create a (3 x 3) array of uniformly-distributed
# random values between 0 and 1
np.random.random((3, 3))

In [ ]:
# Create a (3 x 3) array of normally-distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

In [ ]:
# Create a (3 x 3) array of random integers in the interval
# [0, 10)
np.random.randint(0, 10, (3, 3))

In [ ]:
# Identity matrix
np.eye(3)

In [11]:
# Create an uninitialized array of 3 integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([  0.00000000e+000,   1.93538748e-309,   4.10074486e-322])

### NumPy Standard Data Types

Because NumPy arrays contain values of a single type, it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard numpy data types are listed [here](http://docs.scipy.org/doc/numpy/user/basics.types.html). Note that when constructing an array, they can be specified using a string, e.g.

``` python
np.zeros(10, dtype='int16')
```

or using the associated numpy object, e.g.

``` python
np.zeros(10, dtype=np.int16)
```


## The Basics of NumPy Arrays

### NumPy Array Attributes

In [4]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # 1D array
x2 = np.random.randint(10, size=(3, 4)) # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

Each array has attributes ndim (giving the number of dimensions), shape (giving thesize of each dimension), and size (giving the total size of the array):

In [5]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

### Array Indexing: Accessing Single Elements

Just like Python lists!

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [6]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x2[2, 0]

1

In [ ]:
x2[2, -1]

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

Unlike Python lists, though, keep in mind that NumPy arrays have a fixed type! This means, for example, that if you attempt to insert a floating point value to an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior!

In [8]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon ( : ) character.

The NumPy slicing syntax follows that of the standard Python list: to access a slice of an array x , use 

```
x[start:stop:step]
```

If any of these are unspecified, they default to the values start=0 , stop= (size of dimension), step=1 .

In [ ]:
x = np.arange(10)
x

In [ ]:
x[::2] # every other element

In [ ]:
x[1::2] # every other element, starting at index 1

In [ ]:
x[::-1] # all elements, reversed

In [ ]:
x[5::-2] # reversed every other from index 5

In [ ]:
x2

In [ ]:
x2[:2, :3] # two rows, three columns

In [ ]:
x2[:3, ::2] # all rows, every other column

In [ ]:
x2[::-1, ::-1] # subarray dimension reversed together

#### Accessing Array Rows and Columns

This can be done ccombining indexing and slicing, using an empty slice marked by a single colon ```( : )```:

In [ ]:
print(x2[:, 0]) # first column
print(x2[0, :]) # first row
print(x2[0]) # equivalent to x2[0, :]

#### Subarrays as no-copy views

One important – and extremely useful – thing to know about array slices is that they return views rather than copies of the array data. (If you’re familiar with Python lists, keep in mind that this is different behavior: In lists, slices are copies by default) 

Consider our two-dimensional array from above:

In [9]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [10]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [11]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [12]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This is actually an extremely useful default behavior: it means that when we work with large datasets, we can access and process pieces of these datasets without copying the underlying data buffer. This works because NumPy arrays have a very flexible internal representation

#### Creating Copies of Arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [13]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3x3 grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

Another common reshaping pattern is the conversion of a 1D array into a 2D row or column matrix. This can be done with the reshape method, or more easily done by making use of the ```newaxis``` keyword within a slice operation:

In [ ]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))


# row vector via newaxis
x[np.newaxis, :]


# column vector via reshape
x.reshape((3, 1))


# column vector via newaxis
x[:, np.newaxis]

### Array Concatenation and Splitting

#### Concatenation of Arrays

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [ ]:
# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

Similary, ```np.dstack``` will stack three-dimensional arrays along the third axis.

#### Splitting of Arrays

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # split at indexes 3 and 5
print(x1, x2, x3)

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

## Random Number Generation

### Understanding a Simple “Random” Sequence

While it is possible to obtain sequences of truly random numbers through physical means (by, e.g. monitoring decay events of a radioactive substance) most algorithmic random number generators used in practice are simple deterministic algorithms designed to produce a sequence of pseudo-random numbers with suitable properties.

The simplest of these are linear congruential generators, which generate a sequence of integers r i using the following recursive form:

r<sub>i + 1</sub> = (ar<sub>i</sub>) + c MOD m

where a, c, and m are chosen such that the resulting numbers have useful properties. For example, we can follow Knuth and Lewis who suggest generating 32-bit uniform deviates using m = 2<sup>32</sup> , a = 1664525, and c = 1013904223. We can implement this step simply in Python:

In [ ]:
def LCG_next(r, a=1664525, c=1013904223, m=2 ** 32):
    """
    Generate the next pseudorandom number
    using a Linear Congruential Generator
    """
    return (a * r + c) % m

In [ ]:
seed = 0
for i in range(5):
    seed = LCG_next(seed)
    print(seed)

Often, rather than creating a sequence of integers, it is more convenient to create a sequence of uniform deviates: that is, numbers distributed uniformly in the half-open interval [0, 1). Here we’ll implement this by making use of Python’s convenient generator syntax. We’ll also add code which will automatically seed the sequence based on the current microseconds in the system clock.

In [2]:
from datetime import datetime
from itertools import islice

In [3]:
def LCG_generator(seed=None, a=1664525, c=1013904223, m=2 ** 32):
    """
    Linear Congruential generator of pseudorandom numbers
    """
    if seed is None:
        # If seed is not provided, use current microseconds
        seed = datetime.now().microsecond
        
    while True:
        seed = LCG_next(seed, a=a, c=c, m=m)
        yield float(seed) / m

In [4]:
def simple_uniform_deviate(N, seed=None):
    """
    return a list of N pseudorandom numbers
    in the interval [0, 1)
    """
    gen = LCG_generator(seed)
    return list(islice(gen, N))

In [5]:
# Print a list of 5 random numbers
simple_uniform_deviate(5)

NameError: global name 'LCG_next' is not defined

We’ve started with a seed value, which defaults to some changing
value or other source of pseudo-randomness available in the operating system. Fromt his seed, we construct an algorithm which creates a deterministic sequence of values which are sufficiently random for our purposes. All pseudorandom number generators share this determinism.

Below we’ll see some more efficient and sophisticated random number generators built-in to Python and to NumPy. Despite their complexity, under the hood they are just deterministic algorithms which step from one seed to the next, albeit with more involved steps than we used above.

### Efficient Random Numbers: ```numpy.random```

Python has a built-in random module which uses the sophisticated Mersenne Twister algorithm to generate sequences of uniform pseudorandom numbers.

``` python
import random
[random.random() for i in range(5)]
```

The ```numpy.random``` submodule, like Python’s built-in random module, is based on the Mersenne Twister algorithm. Unlike the Python’s built-in tools, it is optimized for generating large arrays of random numbers.

#### Uniform Deviates
The basic interface is the rand function, which generates uniform deviates:

In [ ]:
np.random.rand()

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(3, 3)

#### Random Integers

In [ ]:
# 10 random integers in the interval [0, 10)
np.random.randint(0, 10, size=10)

Note that here the upper bound is exclusive: that is, the value 10 will never appear in the above list. A related function is np.random.random_integers , which instead implements an inclusive upper bound:

In [ ]:
# 10 random integers in the interval [0, 10]
np.random.random_integers(0, 10, size=10)

#### Permutations and Selections

In [ ]:
x = np.arange(10)
np.random.permutation(x)

In [ ]:
np.random.choice(x, 10, replace=False)

In [ ]:
np.random.choice(x, 10, replace=True)

Neither of these functions modify the original array; if we’d like to shuffle the array in-place we can use the ```np.random.shuffle``` function:

In [ ]:
print(x)
np.random.shuffle(x)
print(x)

#### Normally-distributed Values

While uniform deviates and collections of integers are useful, there are many other distribution functions that are useful in practice. Perhaps the best-known is the normal distribution.

In [ ]:
# Sequence of normally-distributed values
np.random.randn(10)

In [ ]:
# mean=10, stdev=2, size=(3, 3)
np.random.normal(10, 2, (3, 3))

#### Other Distributions

In [ ]:
# poisson distribution for lambda=5
np.random.poisson(5, size=10)

In [ ]:
# exponential distribution with scale=1
np.random.exponential(1, size=10)

### Simultaneously Using Multiple Chains

Sometimes it is useful to have multiple random number sequences available concur‐
rently; numpy.random provides the RandomState class for this purpose. Under the
hood, the above functions are simply making use of a single global instance of this
class. It can be instantiated and used as follows:

In [ ]:
# instantiate a random number generator
# if seed is not specified, it will be seeded
# with a system-dependent source of randomness
rng = np.random.RandomState(seed=2)

Once this class instance is created, many of the above functions can be used as a
method of the class. For example:

In [ ]:
rng.rand(3, 3)

In [ ]:
rng.randint(0, 10, size=5)

In [ ]:
rng.randn(3, 3)

## Computation on NumPy Arrays: Universal Functions

### The Slowness of Loops

In [ ]:
def compute_reciporicals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1 / values[i]
    return output

In [ ]:
values = np.random.randint(1, 10, size=5)
compute_reciporicals(values)

In [ ]:
big_array = np.random.randint(1, 100, size=1E6)
%timeit compute_reciporicals(big_array)

Each time the
reciporical is computed, Python first examines the object’s type and does a dynamic
lookup of the correct function to use for that type. If we were working in compiled
code instead, this type specification would be known before the code executes and the
result could be computed much more efficiently.

### Introducing UFuncs

For many types of operations, NumPy provides a convenient interface into just this
kind of statically-typed, compiled routine. This is known as a vectorized operation.
This can be accomplished by simply performing an operation on the array, which will
then be applied to each element. The loop over each operation can then be pushed
into the compiled layer of numpy, leading to much faster execution.
Compare the results of the following two:

In [ ]:
print(compute_reciporicals(values))
print(1 / values)

In [ ]:
%timeit (1 / big_array)

This vectorized operation is known as a ufunc in NumPy, short for “Universal Function”.
The main purpose of ufuncs is to quickly execute repeated operations by pushing
the loops down into fast compiled code. They are extremely flexible: above we
saw an operation between a scalar and an array; we can also operate between two
arrays:

In [ ]:
np.arange(5) / np.arange(1, 6)

In [ ]:
x = np.arange(9).reshape((3, 3))
2 ** x

Vectorized operations such as ufuncs are nearly always more efficient than their
counterpart implemented using Python loops. Any time you see such a loop in a
Python script, you should consider whether it can be replaced with a vectorized
expression.

### Exploring NumPy’s UFuncs

Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary
ufuncs, which operate on two inputs. We’ll see examples of both these types of functions
below.

#### Array Arithmetic

In [6]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

('x =', array([0, 1, 2, 3]))
('x + 5 =', array([5, 6, 7, 8]))
('x - 5 =', array([-5, -4, -3, -2]))
('x * 2 =', array([0, 2, 4, 6]))
('x / 2 =', array([0, 0, 1, 1]))
('x // 2 =', array([0, 0, 1, 1]))


In [ ]:
-(0.5*x + 1) ** 2

Each of these arithmetic operations are simply convenient wrappers around specific
functions built-in to NumPy; for example, the + operator is simply a wrapper for the
add function:

In [ ]:
np.add(x, 2)

#### Absolute value

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

#### Trigonometric Functions
NumPy provides a large number of useful ufuncs, and some of the most useful for the
data scientist are the trigonometric functions We’ll start by defining an array of
angles:

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

The values are computed to within machine precision, which is why we values which
should be zero do not always hit exactly zero.

#### Exponents and Logarithms

In [ ]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))

In [ ]:
print("3^x =", np.power(3, x))

In [ ]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

#### Specialized Ufuncs

NumPy has many more ufuncs available including hyperbolic trig functions, bitwise
arithmetic, comparison operators, conversions from radians to degrees, rounding and
remainders, and much more. A look through the numpy documentation can reveal
many interesting functionality.
Another excellent source for more specialized and obscure ufuncs is the scipy.spe
cial submodule. There are far too many functions here to list them all, but we’ll go
over some highlights:

In [ ]:
from scipy import special

In [ ]:
# Bessel functions:
x = [0, 1, 2]
print("J0(x) =", special.j0(x))
print("J1(x) =", special.j1(x))
print("J4(x) =", special.jn(x, 4))

In [ ]:
# Gamma functions (generalized factorials) & related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

In [ ]:
# Error function (Integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

### Advanced Ufunc Features
Ufuncs are very flexible beasts; they implement several interesting and useful features,
which we’ll quickly demonstrate below.
#### Specifying Output
For large calculations, it is sometimes useful to be able to specify the array where the
result of the calculation will be stored. Rather than creating a temporary array, this
can be used to write computation results directly to the memory location where you’d
like them to be. For all ufuncs, this can be done using the out argument of the function:

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

If we had instead written y[::2] = ```2 ** x```, this would have resulted in the creation
of a temporary array to hold the results of ```2 ** x```, followed by a second operation
copying those values into the y array. This doesn’t make much of a difference for such
a small computation, but for very large arrays the memory savings from careful use of
the out argument can be significant.

#### Aggregates
For binary ufuncs, there are some interesting aggregates that can be computed from
Ufuncs. For example, if we’d like to reduce an array with a particular operation, we
can use the reduce method of any ufunc. A reduce repeatedly applies a given operation
to the elements of an array until only a single result is left.
For example, calling reduce on the add ufunc returns the sum of all elements in the
array:

In [ ]:
x = np.arange(1, 6)
np.add.reduce(x)

In [ ]:
np.multiply.reduce(x)

In [ ]:
np.add.accumulate(x)

In [ ]:
np.multiply.accumulate(x)

#### Outer Products
Finally, any ufunc can compute the output of all pairs of two different inputs using
the outer method. This allows you, in one line, to do things like create a multiplication
table:

In [ ]:
x = np.arange(1, 13)
np.multiply.outer(x, x)

## Aggregations: Min, Max, and Everything In Between

### Examples of NumPy Aggregates
Here we’ll give a few examples of NumPy’s aggregates
####Summing the Values in an Array
As a quick example, consider computing the sum of all values in an array. Python
itself can do this using the built-in sum function

In [ ]:
L = np.random.random(100)
sum(L)

In [ ]:
np.sum(L)

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

#### Minimum and Maximum

In [ ]:
min(big_array), max(big_array)

In [ ]:
np.min(big_array), np.max(big_array)

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

#### Multi-dimensional Aggregates

In [ ]:
M = np.random.random((3, 4))
print(M)

In [ ]:
M.sum()

In [ ]:
M.min(axis=0)

In [ ]:
M.max(axis=1)

## Computation on Arrays: Broadcasting
### Introducing Broadcasting
Recall that for arrays of the same size, binary operations are performed on an
element-by-element basis:

In [ ]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

Broadcasting allows these types of binary operations to be performed on arrays of different
size: for example, we can just as easily add a scalar (think of it as a zerodimensional
array) to an array:

In [ ]:
a + 5

We can similarly extend this to arrays of higher dimension. Observe the result when
we add a one-dimensional array to a two-dimensinoal array:

In [ ]:
M = np.ones((3, 3))
M

In [ ]:
M + a

In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

In [ ]:
a + b

Just as above we stretched or broadcasted one value to match the shape of the other,
here we’ve stretched both a and b to match a common shape, and the result is a twodimensional
array!

###Broadcasting in Practice
Broadcasting operation form the core of many examples we’ll see throughout this
book; here are a couple simple examples of where they can be useful:
####Centering an Array
In the previous section we saw that ufuncs allow a NumPy user to remove the need to
explicitly write slow Python loops. Broadcasting extends this ability. One commonlyseen
example is when centering an array of data. Imagine you have an array of ten
observations, each of which consists of three values. Using the standard convention,
we’ll store this in a 10 × 3 array:

In [ ]:
X = np.random.random((10, 3))

We can compute the mean using the mean aggregate across the first dimension:

In [ ]:
Xmean = X.mean(0)
Xmean

And now we can center the X array by subtracting the mean (this is a broadcasting
operation):

In [ ]:
X_centered = X - Xmean

To double-check that we’ve done this correctly, we can check that the centered array
has near zero mean:

In [ ]:
X_centered.mean(0)

#### Plotting a 2D function

In [ ]:
# x and y have 50 steps from 0 to 5
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(z, origin='lower', extent=[0, 5, 0, 5],
           cmap=plt.cm.cubehelix)
plt.colorbar();

### Utility Routines for Broadcasting
np.broadcast and np.broadcast_arrays are utility routines which can help with
broadcasting.
np.broadcast will create a broadcast object which gives the shape of the broadcasted
arrays, and allows iteration through all broadcasted sets of elements:

In [ ]:
x= [['A'],
    ['B']]
y = [[1, 2, 3]]
xy = np.broadcast(x, y)
xy.shape

In [ ]:
for xi, yi in xy:
    print(xi, yi)

np.broadcast_arrays takes input arrays and returns array views with the resulting
shape and structure:

In [ ]:
xB, yB = np.broadcast_arrays(x, y)
print(xB)
print(yB)

## Comparisons, Masks, and Boolean Logic
This section covers the use of Boolean masks to examine and manipulate values
within NumPy arrays. Masking comes up when you want to extract, modify, count, or
otherwise manipulate values in an array based on some criterion: for example, you
might wish to count all values greater than a certain value, or perhaps remove all outliers
which are above some threshold. In NumPy, boolean masking is often the most
efficient way to accomplish these types of tasks.
### Comparison Operators as ufuncs
In section X.X we introduced NumPy’s Universal Functions (ufuncs), and focused in
particular on arithmetic operators. We saw that using +, -, *, /, and others on arrays
leads to elementwise operations. For example, adding a number to an array adds that
number to every element:

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x + 10

NumPy also implements comparison operators such as < (less than) and > (greater
than) as elementwise ufuncs. The result of these comparison operators is always an
array with a boolean data type. All six of the standard comparison operations are
available:

In [ ]:
x < 3 # less than

In [ ]:
x != 3 # not equal

It is also possible to compare two arrays element-by-element, and to include compound
expressions:

In [ ]:
2 * x == x ** 2

Just as in the case of arithmetic ufuncs, these will work on arrays of any size and
shape. Here is a two-dimensional example:

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

In [ ]:
x < 6

### Working with Boolean Arrays

#### Counting Entries
To count the number of True entries in a boolean array, np.count_nonzero is useful:

In [ ]:
# how many values less than six?
np.count_nonzero(x < 6)

We see that there are eight array entries that are less than six. Another way to get at
this information is to use np.sum ; in this case False is interpreted as 0 , and True is
interpreted as 1 :

In [ ]:
np.sum(x < 6)

In [ ]:
# how many values less than six in each row?
np.sum(x < 6, 1)

In [ ]:
# are there any values greater than eight?
np.any(x > 8)

In [ ]:
# are all values less than ten?
np.all(x < 10)

In [ ]:
# are all values in each row less than four?
np.all(x < 8, axis=1)

####Boolean Operators
Above we saw how to count, say, all days with rain less than four inches, or all days
with rain greater than two inches. But what if we want to know about all days with
rain less than four inches AND greater than one inch? This is accomplished through
Python’s bitwise logic operators, & , | , ^ , and ~ , first discussed in Section X.X. Like with
the standard arithmetic operators, NumPy overloads these as ufuncs which work
element-wise on (usually boolean) arrays.
For example, we can address this sort of compound question this way:

In [ ]:
np.sum((inches > 0.5) & (inches < 1))

- & --- np.bitwise_and
- | --- np.bitwise_or
- ^ --- np.bitwise_xor
- ~ --- np.bitwise_not

Using boolean identities, we can answer questions in terms of other boolean operators. Here, we answer the same question in a more convoluted way, using boolean
identites:

In [ ]:
np.sum(~( (inches <= 0.5) | (inches >= 1) ))

####Boolean Arrays as Masks
Above we looked at aggregates computed directly on boolean arrays. A more power‐
ful pattern is to use boolean arrays as masks, to select particular subsets of the data
themselves. Returning to our x array from above, suppose we want an array of all val‐
ues in the array which are less than, say, 5.

In [ ]:
x

In [ ]:
x < 5

In [ ]:
x[x < 5]

###Sidebar: " & " vs. " and “...
One common point of confusion is the difference between the keywords " and " and " or “, and the operators & and | . When would you use one versus the other?

The difference is this: " and " and " or " guage to the truth or falsehood of entire object, while & and | refer to portions of each object.

When you use " and " or " or “, it’s equivalent to asking Python to treat the object as asingle boolean entity. In Python, all nonzero integers will evaluate as True. Thus:

In [ ]:
bool(42), bool(27)

In [ ]:
bool(42 and 27)

In [ ]:
bool(42 or 27)

When you use & and | on integers, the expression operates on the bits of the element, applying the and or the or to the individual bits making up the number:

In [ ]:
print(bin(42))
print(bin(59))

In [ ]:
print(bin(42 & 59))

In [ ]:
bin(42 | 59)

Notice that the corresponding bits (right to left) of the binary representation are com‐
pared in order to yield the result.
When you have an array of boolean values in NumPy, this can be thought of as a
string of bits where 1 = True and 0 = False , and the result of & and | operates simi‐
larly to above:

In [ ]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

Using or on these arrays will try to evaluate the truth or falsehood of the entire array
object, which is not a well-defined value:

In [ ]:
A or B

Similarly, when doing a boolean expression on a given array, you should use | or &
rather than or or and :

In [ ]:
x = np.arange(10)
(x > 4) & (x < 8)

Trying to evaluate the truth or falsehood of the entire array will give the same Val
ueError we saw above:

In [ ]:
(x > 4) and (x < 8)

So remember this: " and " and " or " perform a single boolean evaluation on an entire
object, while & and | perform multiple boolean evaluations on the content (the indi‐
vidual bits or bytes) of an object. For boolean NumPy arrays, the latter is nearly
always the desired operation.
##Fancy Indexing
In the previous section we saw how to access and modify portions of arrays using
simple indices (e.g. arr[0] ), slices (e.g. arr[:5] ), and boolean masks (e.g. arr[arr >
0] ). In this section we’ll look at another style of array indexing, known as fancy index‐
ing. Fancy indexing is like the simple indexing above, but we pass arrays of indices in
place of single scalars. This allows us to very quickly access and modify complicated
subsets of an array’s values.
##Exploring Fancy Indexing
Fancy indexing is conceptually simple: it simply means passing an array of indices to
access multiple array elements at once. For example, consider the following array:

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

In [ ]:
[x[3], x[7], x[2]]

In [ ]:
ind = [3, 7, 4]
x[ind]

When using fancy indexing, the shape of the result reflects the shape of the index
arrays rather than the shape of the array being indexed:

In [ ]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

In [ ]:
X = np.arange(12).reshape((3, 4))
X

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

Notice that the first value in the result is X[0, 2] , the second is X[1, 1] , and the
third is X[2, 3] . The pairing of indices in fancy indexing is even more powerful than
this: it follows all the broadcasting rules that were mentioned in section X.X. So, for
example, if we combine a column vector and a row vector within the indices, we get a
two-dimensional result:

In [ ]:
X[row[:, np.newaxis], col]

In [ ]:
row[:, np.newaxis] * col

###Combined Indexing
For even more powerful operations, fancy indexing can be combined with the other
indexing schemes we’ve seen.

In [ ]:
print(X)

We can combine fancy and simple indices:

In [ ]:
X[2, [2, 0, 1]]

In [ ]:
X[1:, [2, 0, 1]]

In [ ]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

### Generating Indices: np.where
One commonly-seen pattern is to use np.where (or the very similar np.nonzero ) to
generate indices to use within fancy indexing. We saw previously that you can use boolean masks to select certain elements of an array. Here, let’s create a random array
and select all the even elements:

In [ ]:
X = rand.randint(10, size=(3, 4))
X

In [ ]:
evens = X[X % 2 == 0]
evens

In [ ]:
X[np.where(X % 2 == 0)]

In [ ]:
i, j = np.where(X % 2 == 0)
print(i)
print(j)

These indices, like the ones we saw above, are interpreted in pairs: (i.e. the first element is X[0, 1] , the second is X[0, 2] , etc.) Note here that the computation of these
indices is an extra step, and thus using np.where in this manner will generally be less
efficient than simply using the boolean mask itself. So why might you use np.where ?
Many use it because they have come from a language like IDL or MatLab where such
constructions are familiar. But np.where can be useful in itself when the indices
themselves are of interest, and also has other functionality which you can read about
in its documentation.

### Example: Selecting Random Points
One common use of fancy indexing is the selection of subsets of rows from a matrix.
By convention, the values of N points in D dimensions are often represented by a 2-
dimensional, N × D array. We’ll generate some points from a two-dimensional multi‐
variate normal distribution:

In [ ]:
mean = [0, 0]
cov = [[1, 2],
[2, 5]]
X = rand.multivariate_normal(mean, cov, 100)
X.shape

In [ ]:
plt.scatter(X[:, 0], X[:, 1]);

Let’s use fancy indexing to select 20 random points. We’ll do this by first choosing 20
random indices with no repeats, and use these indices to select a portion of the origi‐
nal array:

In [ ]:
indices = np.random.choice(X.shape[0], 20, replace=False)
selection = X[indices] # fancy indexing here
selection.shape

In [ ]:
plt.scatter(X[:, 0], X[:, 1], alpha=0.3)
plt.scatter(selection[:, 0], selection[:, 1],
            facecolor='none', s=200);

### Modifying values with Fancy Indexing
Above we saw how to access parts of an array with fancy indexing. Fancy indexing
can also be used to modify parts of an array.
For example, imagine we have an array of indices and we’d like to set the corresponding items in an array to some value:

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

In [ ]:
x[i] -= 10
print(x)

Notice, though, that repeated indices with these operations can cause some poten‐
tially unexpected results. Consider the following:

In [ ]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

Where did the 4 go? The result of this operation is to first assign x[0] = 4 , followed by x[0] = 6 . The result, of course, is that x[0] contains the value 6.
Fair enough, but consider this operation:

In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

You might expect that x[3] would contain the value 2, and x[3] would contain the
value 3, as this is how many times each index is repeated. Why is this not the case?
Conceptually, this is because x[i] += 1 is meant as a short-hand of x[i] = x[i] +
1 . x[i] + 1 is evaluated, and then the result is assigned to the indices in x. With this
in mind, it is not the augmentation that happens multuple times, but the assignment,
which leads to the rather non-intuitive results.
So what if you want the other behavior where the operation is repeated? For this, you
can use the at() method of ufuncs (available since NumPy 1.8), and do the following:

In [ ]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

The at() method does an in-place application of the given operator at the specified
indices (here, i ) with the specified value (here, 1). Another method which is similar
in spirit is the reduceat() method of ufuncs, which you can read about in the
NumPy documentation.

##Sorting Arrays
This section covers algorithms related to sorting NumPy arrays. These algorithms are
a favorite topic in introductory computer science courses: if you’ve ever taken one,
you probably have had dreams (or, depending on your temperment, nightmares)
about insertion sorts, selection sorts, merge sorts, quick sorts, bubble sorts, and many,
many more. All are means of accomplishing a similar task: sorting the values in a list
or array.
For example, a simple selection sort repeatedly finds the minimum value from a list,
and makes swaps until the list is sorted. We can code this in just a few lines of Python:

In [ ]:
def selection_sort(L):
    for i in range(len(L)):
        swap = i + np.argmin(L[i:])
        (L[i], L[swap]) = (L[swap], L[i])
    return L

In [ ]:
L = np.array([2, 1, 4, 3, 5])
selection_sort(L)

Even selection sort, though, is much better than my all-time favorite sorting algorithms, the bogosort:

In [ ]:
def bogosort(L):
    while np.any(L[:-1] > L[1:]):
        np.random.shuffle(L)
    return L

In [ ]:
L = np.array([2, 1, 4, 3, 5])
bogosort(L)

This silly sorting method relies on pure chance: it shuffles the array repeatedly until the result happens to be sorted

### Fast Sorts in Python

In [ ]:
L = [2, 1, 4, 3, 5]
sorted(L)

In [ ]:
print(L)

In [ ]:
L.sort()
print(L)

### Fast Sorts in NumPy: np.sort and np.argsort

In [ ]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

In [ ]:
x.sort()
print(x)

In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

In [ ]:
x[i]

Sorting Along Rows or Columns
A useful feature of NumPy’s sorting algorithms is the ability to sort along specific
rows or columns of a multi-dimensional array using the axis argument. With it, we
can sort along rows or columns of a two-dimensional array:

In [ ]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

In [ ]:
# sort each column of X
np.sort(X, axis=0)

In [ ]:
# sort each row of X
np.sort(X, axis=1)

### Partial Sorts: Partitioning
Sometimes we don’t care about sorting the entire array, but simply care about finding
the N smallest values in the array. NumPy provides this in the np.partition func‐
tion. np.partition takes an array and a number K ; the result is a new array with the
smallest K values to the left of the partition, and the remaining values to the right, in
arbitrary order:

In [ ]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

##Searching and Counting Values In Arrays
This section covers ways of finding a particular value or particular values in an array
of data. This may sound like it simply requires a linear scan of the data, but when you
know the data is sorted, or if you’re trying to find multiple values at the same time,
there are faster ways to go about it.
###Python Standard Library Tools
Because this is so important, the Python standard library has a couple solutions you
should be aware of. Here we’ll quickly go over the functions and methods Python
contains for doing searches in unsorted and sorted lists, before continuing on to the
more specialized tools in NumPy.
####Unsorted Lists

In [ ]:
L = [5, 2, 6, 1, 3, 6]
L.index(6)

#### Sorted Lists

In [ ]:
import bisect
L = [2, 4, 5, 5, 7, 9]
bisect.bisect_left(L, 7)

Technically, bisect is not searching for the value itself, but for the insertion index:
that is, the index at which the value should be inserted in order to keep the list sorted:

In [ ]:
bisect.bisect(L, 4.5)

In [ ]:
L.insert(2, 4.5)
L == sorted(L)

###Searching for Values in NumPy Arrays
NumPy has some similar tools and patterns which work for quickly locating values in
arrays, but their use is a bit different than the Python standard library approaches.
The patterns listed below have the benefit of operating much more quickly on
NumPy arrays, and of scaling well as the size of the array grows.
####Unsorted Arrays

In [ ]:
A = np.array([5, 2, 6, 1, 3, 6])
np.where(A == 6)

np.where always returns a tuple of index arrays; even in the case of a one-dimensional
array you should remember that the output is a one-dimensional tuple. To isolate the
first index at which the value is found, then, you must use [0] to access the first item
of the tuple, and [0] again to access the first item of the array of indices. This gives
the equivalent result to list.index :

In [ ]:
list(A).index(6) == np.where(A == 6)[0][0]

Note that this masking approach solves a different use-case than list.index : rather
than finding the first occurrance of the value and stopping, it finds all occurrances of
the value simultaneously.

####Sorted Arrays
If your array is sorted, NumPy provides a fast equivalent of Python’s bisect utilities
with the np.searchsorted function:

In [ ]:
A = np.array([2, 4, 5, 5, 7, 9])
np.searchsorted(A, 7)

In [ ]:
np.searchsorted(A, 4.5)

In [ ]:
np.searchsorted(A, [7, 4.5, 5, 10, 0])

###Counting and Binning
A related set of functionality in NumPy is the built-in tools for counting and binning
of values. For example, to count the occurrances of a value or other condition in an
array, use np.count_nonzero :

In [ ]:
A = np.array([2, 0, 2, 3, 4, 3, 4, 3])
np.count_nonzero(A == 4)

In [ ]:
np.unique(A, return_counts=True)

If your data consist of positive integers, a more compact way to get
this information is with the np.bincount function:

In [ ]:
np.bincount(A)

np.bincount can become cumbersome when your values are large,
and it does not apply when your values are not integers. For this more general case,
you can specify bins for your values with the np.histogram function:

In [ ]:
counts, bins = np.histogram(A, bins=range(6))
print("bins:       ", bins)
print("counts in bin: ", counts)

Here the output is formatted to make clear that the bins give the boundaries of the
range, and the counts indicate how many values fall within each of those ranges. For
this reason, the counts array will have one fewer entry than the bins array. A related
function to be aware of is np.digitize , which quickly computes index of the appro‐
priate bin for a series of values.

## Structured Data: NumPy’s Structured Arrays
While often our data can be well-represented by a homogeneous array of values,
sometimes this is not the case. This section demonstrates the use of NumPy’s struc‐
tured arrays and record arrays, which provide efficient storage for compound, hetero‐
geneous data. While the patterns shown here are useful for simple operations,
scenarios like this often lend themselves to the use of Pandas Dataframes, which we’ll
explore in the next chapter.
Imagine that we have several categories of data on a number of people (say, name,
age, and weight), and we’d like to store these values for use in a Python program. It
would be possible to store these in three separate arrays:

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

But this is a bit clumsy. There’s nothing here that tells us that the three arrays are
related; it would be more natural if we could use a single structure to store all of this
data. NumPy can handle this through structured arrays, which are arrays with com‐
pound data types.

Recall that previously we created a simple array using an expression like this:

In [ ]:
x = np.zeros(4, dtype=int)

We can similarly create a structured array using a compound data type specification:

In [ ]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

Here 'U10' translates to “unicode string of maximum length 10”, 'i4' translates to
“4-byte (i.e. 32 bit) integer” and 'f8' translates to “8-byte (i.e. 64 bit) float)”. We’ll
discuss other options for these type codes below.

Now that we’ve created an empty container array, we can fill the array with our lists of
values:

In [ ]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

As we had hoped, the data is now arranged together in one convenient block of memory.

The handy thing with structured arrays is that you can now refer to values either by
index or by name:

In [ ]:
# Get all names
data['name']

In [ ]:
# Get first row of data
data[0]

In [ ]:
# Get the name from the last row
data[-1]['name']

In [ ]:
# Get names where age is under 30
data[data['age'] < 30]['name']

### Creating Structured Arrays
Structured array data types can be specified in a number of ways. Above, we saw the
dictionary method:

In [ ]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

In [ ]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

In [ ]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

### More Advanced Compound Types
It is possible to define even more advanced compound types. For example, you can
create a type where each element contains an array or matrix of values. Here, we’ll
create a data type with a mat component consisting of a 3x3 floating point matrix:

In [ ]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

### RecordArrays: Structured Arrays with a Twist
NumPy also provides the np.recarray class, which is almost identical to the struc‐
tured arrays described above with one additional feature: fields can be accessed as
attributes rather than as dictionary keys. Recall that we previously accessed the ages
by writing:

In [ ]:
data['age']

If we view our data as a record array instead, we can access this with slightly fewer
keystrokes:

In [ ]:
data_rec = data.view(np.recarray)
data_rec.age

The downside is that for record arrays, there is some extra overhead involved in
accessing the fields, even when using the same syntax. We can see this here:

In [ ]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age